name: GDrive Video Processing 


# Run with a CURL request:
# 
# curl                                                            \                                    
# -X POST                                                         \                                   
# -H "Accept: application/vnd.github+json"                        \                  
# -H "Authorization: Bearer GITHUB_PAT_KEY"                       \                  
# -H "X-GitHub-Api-Version: 2022-11-28"                           \                    
#     https://api.github.com/repos/ioroot/ffmpeg__bash-scripts/dispatches \         
#     -d '{"event_type":"run_autoflip","client_payload":{         \         
#             "GDRIVE_FOLDER":  "FOLDER/IN/GDRIVE/TO/USE",        \            
#         }                                                       \


on:

  # Via a webhook
  repository_dispatch:
    types: gdrive_video_convert

env:


  # ╭──────────────────────────────────────────────────────────╮
  # │                Target Google Sheet Script                │
  # ╰──────────────────────────────────────────────────────────╯
  SHEETS: "https://script.google.com/macros/s/AKfycbwrzBUwTlj7gOJ87U0D0hQnkiRMMEwphLz-MPNw2mYrZw0FBEEOkTHkGp6QsQgKqRCK/exec"

  # ╭──────────────────────────────────────────────────────────╮
  # │                        Video URL                         │
  # │        1. Get Data from CURL request and webhook         │
  # │            2. or Get URL from commit message             │
  # ╰──────────────────────────────────────────────────────────╯
  GDRIVE_FOLDER_PREFIX:     "/SocialExporter/videos/"
  GDRIVE_FOLDER:            ${{ github.event.client_payload.GDRIVE_FOLDER }} 
  

  # ╭──────────────────────────────────────────────────────────╮
  # │                Aspect Ratio to output as.                │
  # ╰──────────────────────────────────────────────────────────╯
  TEMPLATE:             ${{ github.event.client_payload.TEMPLATE }}



jobs:

  build:


    runs-on: ubuntu-latest
    container:
      
    steps:

      # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#repository_dispatch
      # https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#create-a-repository-dispatch-event
      - name: Test the repository_dispatch fields
        run: |
            echo "GDRIVE_FOLDER: ${GDRIVE_FOLDER}/raw"
            echo "TARGET_OUTPUT_FOLDER: ${GDRIVE_FOLDER}/processed"
            echo "TEMPLATE: ${TEMPLATE}"
            


      - name: install dependencies
        run: |
          sudo apt-get update 
          sudo apt-get install --no-install-recommends ffmpeg rclone

      - name: Checkout Repo
        uses: actions/checkout@v3


      - name: rclone
        uses: wei/rclone@v1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        with:
          args: copy GDrive:${GDRIVE_FOLDER_PREFIX}${GDRIVE_FOLDER} ./raw_videos


      - name: run ffmpeg template
        run: |
            ls -la ./raw_videos
            mkdir -p ./processed_videos
            cd ./templates
            ./ft_simple_1-1.sh -f ../raw_videos/raw -o ../processed_videos/processed.mp4

            
      - name: rclone
        uses: wei/rclone@v1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        with:
          args: copy ./processed_videos GDrive:${GDRIVE_FOLDER_PREFIX}${GDRIVE_FOLDER}/processed
